### ISSUE TITLE
Flaky test in `mitiq/zne/tests/test_zne.py`

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2442] opened 2024-07-06 01:28 UTC
Noticed the failure here: https://github.com/unitaryfund/mitiq/actions/runs/9814019705/job/27101033866#step:6:4363

If I rerun the workflow, the test passes. 

![image](https://github.com/unitaryfund/mitiq/assets/66048318/328732a8-e757-4f5c-bc3d-f6516735f688)

https://github.com/unitaryfund/mitiq/blob/e61c058777b11cc34b81be05e78b1c4bc91d7775/mitiq/zne/tests/test_zne.py#L81-L101

https://github.com/unitaryfund/mitiq/blob/e61c058777b11cc34b81be05e78b1c4bc91d7775/mitiq/interface/mitiq_cirq/cirq_utils.py#L17

**Comment by cosenal** [comment] 2024-08-15 02:59
Closing as dupe of #1896.

**Closed by cosenal** 2024-08-15 02:59 UTC
Labels: bug, zne, os: windows, os: mac
