### ISSUE TITLE
Code duplication in factories

### ISSUE THREAD

**Issue by rmlarose** [unitaryfund/mitiq#455] opened 2020-11-25 17:01 UTC
The `reduce` method is identically re-defined in every instance of a batched factory. See

- https://github.com/unitaryfund/mitiq/blob/master/mitiq/zne/inference.py#L807
- https://github.com/unitaryfund/mitiq/blob/master/mitiq/zne/inference.py#L901
- https://github.com/unitaryfund/mitiq/blob/master/mitiq/zne/inference.py#L993
- https://github.com/unitaryfund/mitiq/blob/master/mitiq/zne/inference.py#L1136
- https://github.com/unitaryfund/mitiq/blob/master/mitiq/zne/inference.py#L1462

The only unique part is the `extrapolate` method, so this should be the `abstractmethod` in batched factory and `reduce` should a method of batched factory.

**Comment by elmandouh** [comment] 2020-11-29 10:26
There are several ways to go about doing this. The simplest approach, but not necessarily the most elegant, is to introduce the following:

```
    def reduce(self) -> float:
        """Evaluates the zero-noise limit found by fitting according to
        the factory's extrapolation method.

        Returns:
            The zero-noise limit.
        """
        # Some factories do not have an order attribute
        order = self.order if hasattr(self, 'order') else None
        (
            self._zne_limit,
            self._zne_error,
            self._opt_params,
            self._params_cov,
            self._zne_curve,
        ) = self.extrapolate(  # type: ignore
            self.get_scale_factors(),
            self.get_expectation_values(),
            order=order,
            full_output=True
        )
        
        self._already_reduced = True
        return self._zne_limit
```

We can avoid having to check for the `order` attribute if we refactor so that all instances have `order` attribute (None as default). Another way is to pass the object to `extrapolate` instead of the parameters. That would mean that `extrapolate` is no longer a static method.

I prefer the first approach's simplicity. I can open up a PR after receiving some feedback and closing #444.

**Comment by andreamari** [comment] 2020-11-30 10:54
Hi @rmlarose  and @elmandouh, 

As @elmandouh noticed, the problem with this issue is that the way to use the `extrapolate` function is factory-dependent, since the arguments are usually different. 
The argument `order` is not the only example: `ExpFactory` , `PolyExpFactory` and `AdaptiveFactory` have other options too ( e.g. `asymptote`, "avoid_log", `eps`). 

Given this fact, we could decide to keep factory-specific reduce methods or we could still try to force all cases into a unique base `reduce`. I just wanted to point out that the issue is less trivial than it seems.

**Comment by elmandouh** [comment] 2020-11-30 11:33
@andreamari `order` is indeed not the only attribute we need to check for. By forcing all cases into one `reduce` we would make it difficult to maintain and extend in the future. Thus, I believe keeping the factory specific reduce methods is the better option. There are other approaches I can pursue, but they would require major refactoring and the payoff doesn't seem worth it.

**Comment by rmlarose** [comment] 2020-11-30 17:48
What about a new method which returns the extra arguments to `extrapolate` for each factory? i.e.

```python
class Factory:
  @abstractmethod
  def _extrapolate_args(self) -> Dict[str, Any]:
    # For example in PolyFac, return {"order": self.order, ...}

  @abstractmethod
  @staticmethod
  def extrapolate(*args, **kwargs):

  def reduce(self) -> float:
    (
      self._zne_limit,
      self._zne_error,
      self._opt_params,
      self._params_cov,
      self._zne_curve,
    ) = self.extrapolate(  # type: ignore
      self.get_scale_factors(),
      self.get_expectation_values(),
      full_output=True,
      **self._extrapolate_args(),
      )
      self._already_reduced = True
      return self._zne_limit
```

In this way `reduce` doesn't need to be redefined, only `_extrapolate_args`, unless I'm missing something. 

Anyhow, I completely agree this is low priority, just something I noticed in `inference.py` which I thought could be cleaned up without too much hassle. If not let's ignore it.

**Closed** 2021-01-06 14:47 UTC
