### ISSUE TITLE
Techniques missing from top level `__init__.py`.

### ISSUE THREAD

**Issue by natestemen** [unitaryfund/mitiq#2202] opened 2024-02-22 06:28 UTC
Only a subset of QEM techniques in Mitiq are in the top level `__init__.py` file.
https://github.com/unitaryfund/mitiq/blob/c5afbd4df6850cacc331a1aa1a477265d4bb584a/mitiq/__init__.py#L29

This means to use the newer techniques such as shadows, QSE, and twirling, you must use the full path as demonstrated in the [shadows tutorial](https://mitiq.readthedocs.io/en/stable/examples/shadows_tutorial.html). This also manifested when I was trying to test `mitiq.pt` locally and noticed that when I tried to run `>>> mitiq.pt` I got `AttributeError: module 'mitiq' has no attribute 'pt'`.

We should add all the techniques/modules we have here.

**Comment by natestemen** [comment] 2024-02-27 18:49
So I'm not entirely sure why I was seeing this error. When taking a look with Misty a day or so after raising this issue, I was not able to reproduce.

We opened #2206 while investigating this as we realized we had some unnecessary imports. Technically, #2206 does not "fix" this issue, as there **isn't** a reproducible issue. Still, good to have redundant code removed so will go ahead with merging that PR. I'm going to close this now just to indicate that technically #2206 does not "fix" this issue.

**Comment by FarLab** [comment] 2024-02-28 14:05
Thanks for documenting this!

**Comment by purva-thakre** [comment] 2024-04-19 19:20
Reopening this https://github.com/unitaryfund/mitiq/commit/ae7dad90b659af89d97227a3da37f89e638ae657#r141079046

**Comment by natestemen** [comment] 2024-04-19 19:35
@purva-thakre can you document a minimally reproducible process for how to recreate this bug?

**Comment by purva-thakre** [comment] 2024-04-19 19:46
Pinging @jordandsullivan for the workflow on how to recreate this bug as they came across it initially. https://github.com/unitaryfund/mitiq/pull/2298#issuecomment-2060171860

I was trying to understand why it could be so.

**Comment by jordandsullivan** [comment] 2024-04-19 22:49
This is how you reproduce which modules are throwing this error:
```python
from types import ModuleType
import mitiq 

mod_list = [
    'mitiq.cdr', 
    'mitiq.ddd', 
    'mitiq.pec', 
    'mitiq.pt', 
    'mitiq.qse', 
    'mitiq.rem', 
    'mitiq.zne'
    ]
for module in mod_list:
    try:
        assert isinstance(eval(module), ModuleType)
    except Exception as e:
        print(module, e)
```
which gives the following output:
```python
mitiq.ddd module 'mitiq' has no attribute 'ddd'
mitiq.pt module 'mitiq' has no attribute 'pt'
mitiq.qse module 'mitiq' has no attribute 'qse'
mitiq.rem module 'mitiq' has no attribute 'rem'
```

**Comment by natestemen** [comment] 2024-04-19 23:45
Huh weird! I don't quite understand why it's complaining given you can still run code such as
```py
import mitiq.ddd
from mitiq import ddd
```

I did notice that the above code snippet does not error on `ddd` and `rem` when running on the commit before (9bea1554a02a1913d59d98e09746ad7631500125) we removed some imports in the top level `__init__.py` file in https://github.com/unitaryfund/mitiq/pull/2206.

As far as I understand, this shouldn't effect any use cases of Mitiq, so going to tag this as low priority, but I'm very curious to learn what's the difference between how python treats these modules.

**Comment by jordandsullivan** [comment] 2024-04-22 19:24
Agreed, low priority; it's just going to bother me in the back of my mind until I figure out why it's happening XD

**Comment by cosenal** [comment] 2024-04-29 09:55
My 2c: this is happening because in `mitiq/__init__.py`  indirectly imports some of the modules, but not others. E.g. in [this line](https://github.com/unitaryfund/mitiq/blob/fe3a6669c3fe2d7197ab02fa37765653392ee97e/mitiq/__init__.py#L28) we import from settings.py, which in turns imports `mitiq.zne` at the [top of the file](https://github.com/unitaryfund/mitiq/blob/866d45e91307283a5f826f6a501e6303423e1891/mitiq/calibration/settings.py#L24). It so happens that `mitiq.ddd` is not imported in this "DAG of imports", but so be it, it's not a problem in my opinion. When a module is imported, it ends up in the attributes as well, so you can do `eval('mitiq.zne')`.
The `import` actually try to discovers the modules into the filesystem paths (connected to the reason why we never managed to alias `mitiq.qem.zne` to `mitiq.zne`). 
This is why you can do `import mitiq.ddd`, but you `mitiq` doesn't have `ddd` as an attribute. Not very interesting to be honest, we can close this, until there is a very good reason to inspect mitiq attributes with `eval

**Comment by jordandsullivan** [comment] 2024-05-10 18:23
Closing given discussion above.

**Closed by jordandsullivan** 2024-05-10 18:23 UTC
Labels: tech debt, priority/low
