### ISSUE TITLE
`macos-latest` is incompatible with Python versions < `3.11, 3.12`

### ISSUE THREAD

**Issue by purva-thakre** [unitaryfund/mitiq#2339] opened 2024-05-01 02:07 UTC
Related to https://github.com/actions/runner-images/issues/9770

We use `macos-latest` in our GIthub workflows. For the jobs that run on Python 3.9 and Python 3.10, we get a notice to use `python3.x -m pip install --upgrade pip` instead of `python -m pip install --upgrade pip`

![image](https://github.com/unitaryfund/mitiq/assets/66048318/ab7a2144-cd28-487b-a92e-3e392d0a9429)

https://github.com/unitaryfund/mitiq/actions/runs/8899188557

**Option 1 -** Downgrade to an earlier version of `macos`
**Option 2 -** Don't run these jobs on `macos` for Python 3.9 and Python 3.10

**Comment by cclauss** [comment] 2024-05-01 11:03
Those are WARNINGS, not ERRORS.  They can be solved with `pip install --upgrade pip`

**Comment by cosenal** [comment] 2024-05-01 15:47
@purva-thakre isn't this a dupe of https://github.com/unitaryfund/mitiq/issues/2321? If so, I closed it as resolved, because it was fixed in https://github.com/actions/python-versions/pull/264. In which _recent_ build do you see the warnings/errors?

**Comment by cosenal** [comment] 2024-05-01 16:09
I clicked on that link and I don't see the macos builds failing 🤔

**Comment by purva-thakre** [comment] 2024-05-01 16:10
it's not failing for me either. The screenshot is from the annotation at the bottom.

**Comment by cosenal** [comment] 2024-05-01 16:13
As @cclauss said, those annotations are warnings about `pip`, not related to what you say in the title of the issue.

**Comment by purva-thakre** [comment] 2024-05-01 16:17
@cosenal Yeah, I'll try to understand their comment later today because I somehow connected the `pip` warning to the missing python versions. 🤷🏾‍♀️

Feel free to close this or change the title/issue description as required.

**Comment by cosenal** [comment] 2024-05-01 16:22
I will close this. The notices you see at the bottom of the runs are about upgrading pip in those runners we use in the github workflows. This is not something that is affecting Mitiq or its builds at the moment.

**Closed by cosenal** 2024-05-01 16:22 UTC
