### ISSUE TITLE
Add notebooks from Mitiq paper to the examples section

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#761] opened 2021-06-28 15:53 UTC
Add Jupyter notebooks (or in md, rst or myst format) from the Mitiq paper v2 to be updated on the arXiv (https://arxiv.org/abs/2009.04417) to the examples section of the documentation. 

- This should be a new section under the Mitiq examples, https://mitiq.readthedocs.io/en/stable/examples/examples.html

- This should be also referenced in the Research section of the documentation, https://mitiq.readthedocs.io/en/stable/research.html

- Some examples may contain data as for the Rigetti experiments, to be linked in a data file. It has been proposed that these could be optionally downloaded, not by default if one clones the repo. 

- We discussed adding a tag for the relevant v2 version.

- We also need to choose if we want these to be updated continually or not as they may get out of date with the current status of Mitiq. If they are built as part of the documentation they need to work always, otherwise they could simply be some .py files to be linked to the examples section as an archive.

**Comment by crazy4pi314** [comment] 2021-06-29 06:32
Is this a duplicate of #759 ?

**Comment by rmlarose** [comment] 2021-06-30 17:52
There's three issues open for this now - this one, #759, and #775. Can we please consolidate @nathanshammah?

**Closed** 2021-07-07 17:11 UTC
Labels: documentation, feature-request
