### ISSUE TITLE
Further automate allcontributors

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#1465] opened 2022-08-26 16:30 UTC
Further automate allcontributors. Ideally, we'd like it to:
1. autonomously detect a new contributor
2. categorize the contribution automatically. If there is a way to tell allcontributors that for example, files modified under `/docs/` should add a "documentation" feature, `/test/` adds the testing one... etc.

This could work in a way like one of the following:
1. allcontributors automatically comments on the PR and the user replies with an emoji to vouch for the proposal
2. all contributors checks if there are new contributors in commits merged to master and then creates a new PR

**Comment by nathanshammah** [comment] 2022-09-27 09:26
I don't remember, @Aaron-Robertson is this something you are looking into?

**Comment by natestemen** [comment] 2022-10-27 22:14
duplicate of https://github.com/unitaryfund/mitiq/issues/1036

**Closed by natestemen** 2022-10-27 22:14 UTC
Labels: documentation, good first issue, infrastructure, feature-request
