### ISSUE TITLE
Understand unwanted inclusion of docstring of imported function

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/mitiq#639] opened 2021-04-16 08:49 UTC
Pre-Report Checklist
--------------------

- [x] I am running the latest version of mitiq
- [x] I checked to make sure that this bug has not already been reported

Issue Description
-----------------
The pull request on the first part of the Clifford Data Regression methods, #601 has had a test of the docs failing apparently due to a docstring in which the actual code run of the example does not match the expected outcome. However, the docstring does not seem present in the Mitiq codebase, but would seem to be picked up by some backtracking of imported python / numpy functions. 

Moreover, the API-doc showed in the docstring a part that would seem to belong to the imported function.    

How to Reproduce
----------------
The CI error is shown in https://github.com/unitaryfund/mitiq/pull/601/checks?check_run_id=2254832392.

The docstring being picked up by Sphinx in the API-doc was due to the code in #601 by @L-P-B before the changes in the code base at [this commit](https://github.com/unitaryfund/mitiq/pull/601/commits/ec1d6edac2784624f091deb717a09ebf52370761) by @maikthomas.  

The inclusion of the docstring could be reproduced by running `make docs` locally before the commit above, which builds the documentation with sphinx. Here is a screenshot of the API-doc: 
<img width="885" alt="ctd" src="https://user-images.githubusercontent.com/14573436/114998490-e9d1f200-9e98-11eb-99aa-85a52fae31c1.png">

**Comment by rmlarose** [comment] 2021-06-07 22:56
Closing as the issue is no longer present - I think this is outdated.

**Closed by rmlarose** 2021-06-07 22:56 UTC
Labels: documentation, help wanted, question
